// <auto-generated />
// This is a generated C# file which should be skipped by the Action reviewer
// so that we don't spam or crash on automatically generated code.
public class AutoGeneratedClass
{
    public void DoSomething()
    {
        // Even if it has an issue like task.Result, it should be skipped
        var res = System.Threading.Tasks.Task.FromResult(42).Result;
    }
}
